name: Run V2ray Bot
on:
  schedule:
    - cron: '*/30 * * * *' # هر 30 دقیقه یکبار اجرا می‌شود
  workflow_dispatch:

permissions:
  contents: write # اجازه ذخیره فایل‌های حافظه در گیت‌هاب

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install requests jdatetime pytz beautifulsoup4
          
      - name: Run Bot
        run: python bot.py
        
      - name: Save memory file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sent_configs.txt state.txt
          git diff --staged --quiet || git commit -m "Update memory files"
          for i in 1 2 3; do
            git pull --rebase origin main
            if git push origin main; then
              break
            fi
            sleep 5
          done
